# Generated by Django 3.2.8 on 2021-12-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('China', 'China'), ('Korea', 'Korea'), ('Brazil', 'Brazil')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('India', 'India'), ('China', 'China'), ('Korea', 'Korea'), ('Brazil', 'Brazil')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('price', models.FloatField(default=0.0)),
                ('release_date', models.DateField(auto_now_add=True, null=True)),
                ('length', models.TimeField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, to='movie_app.Actors')),
                ('category', models.ManyToManyField(blank=True, to='movie_app.Category')),
                ('languages', models.ManyToManyField(blank=True, to='movie_app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MyMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actors',
            name='languages',
            field=models.ManyToManyField(blank=True, to='movie_app.Language'),
        ),
    ]
