# Generated by Django 3.2.8 on 2021-12-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0003_alter_movie_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=150)),
                ('TXNID', models.CharField(max_length=150)),
                ('TXNAMOUNT', models.FloatField()),
                ('CHECKSUMHASH', models.CharField(blank=True, max_length=150)),
                ('BANKTXNID', models.CharField(blank=True, max_length=150)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=100)),
                ('TXNDATE', models.DateTimeField(auto_now_add=True, null=True)),
                ('BANKNAME', models.CharField(blank=True, max_length=100)),
                ('RESPMSG', models.CharField(blank=True, max_length=500)),
                ('STATUS', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
