# Generated by Django 3.2.8 on 2021-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_auto_20211212_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
