# Generated by Django 3.2.8 on 2021-12-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_auto_20211212_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
            preserve_default=False,
        ),
    ]
