# Generated by Django 3.2.8 on 2021-12-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_auto_20211212_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('China', 'China'), ('Korea', 'Korea'), ('Brazil', 'Brazil')], max_length=200),
        ),
    ]
