# Generated by Django 3.2.8 on 2021-12-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_subscription_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='photo',
            new_name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.CreateModel(
            name='MoviesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movies/images/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.actors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='movie_photos', to='movie_app.MoviesPhoto'),
        ),
    ]
